// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApp.Data.Concrete.EntityFramework.Contexts;

namespace MyWebApp.Data.Migrations
{
    [DbContext(typeof(MyWebAppContext))]
    [Migration("20220319222721_xl")]
    partial class xl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("MyWebApp.Entities.Concrete.AboutMe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MyCVPath")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("MyJob")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MyJobFA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("AboutMe");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2022, 3, 20, 1, 27, 20, 933, DateTimeKind.Local).AddTicks(9587),
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 934, DateTimeKind.Local).AddTicks(10),
                            FirstName = "Hasan",
                            ImagePath = "",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Erdal",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 934, DateTimeKind.Local).AddTicks(289),
                            MyCVPath = "",
                            MyJob = "Full-stack Web Developer",
                            MyJobFA = "<i class=\"fas fa - laptop - code\"></i>",
                            Note = "InitialCreate"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SQAnswerHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SecurituQuestion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 936, DateTimeKind.Local).AddTicks(179),
                            Email = "hasaerda@hotmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 936, DateTimeKind.Local).AddTicks(184),
                            Note = "InitialCreate",
                            PasswordHash = "C863FB7DD9E5A18B8F142DB629FA563A",
                            SQAnswerHash = "fb01c2637b1583bd8e911f6ff47017c7",
                            SecurituQuestion = "Anne kızlık soyadı (küçük harflerle)?"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SeoDescription")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SeoTags")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("ShortContent")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Content = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 942, DateTimeKind.Local).AddTicks(7885),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 942, DateTimeKind.Local).AddTicks(7899),
                            Note = "InitialCreate",
                            SeoDescription = "C# 9.0 ve .Net 5.0 Yenilikleri",
                            SeoTags = "C#, C#9, .NET5",
                            ShortContent = "",
                            Thumbnail = "",
                            Title = "C# 9.0 ve .Net 5.0 Yenilikleri",
                            ViewsCount = 0
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryFA")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryFA = "<i class=\"fas fa - code\"></i>",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 944, DateTimeKind.Local).AddTicks(480),
                            Description = "Yazılım ile ilgili güncel bilgiler içerir.",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 944, DateTimeKind.Local).AddTicks(486),
                            Name = "Yazılım",
                            Note = "InitialCreate"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 945, DateTimeKind.Local).AddTicks(5506),
                            FirstName = "Hasan",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Erdal",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 945, DateTimeKind.Local).AddTicks(5568),
                            Note = "C# Blog Gönderisi",
                            Text = "Bu bir deneme yorumudur. Lütfen dikkate almayınız!"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LongAdress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ShortAdress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ContactInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 946, DateTimeKind.Local).AddTicks(8587),
                            Email = "hasaerda@hotmail.com",
                            IsActive = true,
                            IsDeleted = false,
                            LongAdress = "Yukarıbayır Mh. Hüseyin Aşkın Sk. No:44 Kat-1",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 946, DateTimeKind.Local).AddTicks(8594),
                            Note = "InitialCreate",
                            PhoneNumber = "+905370352059",
                            ShortAdress = "Şahinbey/Gaziantep"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Avarage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Educations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avarage = "2.65 GANO",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 948, DateTimeKind.Local).AddTicks(2989),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem recusandae quibusdam expedita, vitae veniam aut",
                            Duration = "Eylül 2016--Devam Ediyor",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 948, DateTimeKind.Local).AddTicks(2997),
                            Note = "InitialCreate",
                            School = "Uludağ Üniversitesi-Elektrik Elektronik Müh",
                            Title = "Lisans Derecesi"
                        },
                        new
                        {
                            Id = 2,
                            Avarage = "81.63 ORT",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 948, DateTimeKind.Local).AddTicks(3007),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Exercitationem recusandae quibusdam expedita, vitae veniam aut",
                            Duration = "Eylül 2012--Temmuz 2016",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 948, DateTimeKind.Local).AddTicks(3008),
                            Note = "InitialCreate",
                            School = "Türkan Halit Aykılıç Fen Lisesi-Fen Bilimleri",
                            Title = "Lise Mezun"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Workplace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 949, DateTimeKind.Local).AddTicks(7495),
                            Description = "Haziran 2020'den beridir, arkadaşlar ve çevrwm için web sitesi yapıyorum. Birkaç tanesini yayına aldım.",
                            Duration = "Haziran 2020--Devam Ediyor",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 949, DateTimeKind.Local).AddTicks(7502),
                            Note = "InitialCreate",
                            Title = "Freelance Web Developer",
                            Workplace = "Freelance"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.HomePageSlider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("HomePageSliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 951, DateTimeKind.Local).AddTicks(443),
                            IsActive = true,
                            IsDeleted = false,
                            LongDescription = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur. Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 951, DateTimeKind.Local).AddTicks(449),
                            Note = "InitialCreate",
                            ShortDescription = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır.",
                            Title = ".NET DEVELOPER"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 951, DateTimeKind.Local).AddTicks(459),
                            IsActive = true,
                            IsDeleted = false,
                            LongDescription = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur. Yaygın inancın tersine, Lorem Ipsum rastgele sözcüklerden oluşmaz. Kökleri M.Ö. 45 tarihinden bu yana klasik Latin edebiyatına kadar uzanan 2000 yıllık bir geçmişi vardır. Virginia'daki Hampden-Sydney College'dan Latince profesörü Richard McClintock, bir Lorem Ipsum pasajında geçen ve anlaşılması en güç sözcüklerden biri olan 'consectetur' sözcüğünün klasik edebiyattaki örneklerini incelediğinde kesin bir kaynağa ulaşmıştır. Lorm Ipsum, Çiçero tarafından M.Ö. 45 tarihinde kaleme alınan \"de Finibus Bonorum et Malorum\" (İyi ve Kötünün Uç Sınırları) eserinin 1.10.32 ve 1.10.33 sayılı bölümlerinden gelmektedir. Bu kitap, ahlak kuramı üzerine bir tezdir ve Rönesans döneminde çok popüler olmuştur. Lorem Ipsum pasajının ilk satırı olan \"Lorem ipsum dolor sit amet\" 1.10.32 sayılı bölümdeki bir satırdan gelmektedir.",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 951, DateTimeKind.Local).AddTicks(460),
                            Note = "InitialCreate",
                            ShortDescription = "Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır.",
                            Title = "WEB DEVELOPER"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Interested", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Interesteds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 952, DateTimeKind.Local).AddTicks(622),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 952, DateTimeKind.Local).AddTicks(628),
                            Note = "InitialCreate",
                            Text = "Bilgisayar Donanımları, Bileşenleri ve Yazılımları"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 952, DateTimeKind.Local).AddTicks(638),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 952, DateTimeKind.Local).AddTicks(638),
                            Note = "InitialCreate",
                            Text = "Vizyon Filmlerini takip etmek ve izlemek, Film incelemelerini okumak, Parodileri izlemek"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 952, DateTimeKind.Local).AddTicks(642),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 952, DateTimeKind.Local).AddTicks(643),
                            Note = "InitialCreate",
                            Text = "Animeler ve Mangalar"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 953, DateTimeKind.Local).AddTicks(5038),
                            Email = "deneme@mail.com",
                            FirstName = "Mehmet",
                            IsActive = true,
                            IsDeleted = false,
                            LastName = "Şevket",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 953, DateTimeKind.Local).AddTicks(5044),
                            Note = "InitialCreate",
                            Subject = "deneme",
                            Text = "Bu bir deneme mesajıdır. Dikkate almayınız!"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.SiteIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogoFA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LogoText")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SiteIdentity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 954, DateTimeKind.Local).AddTicks(7562),
                            Description = "Ben Hasan Erdal. Yazılım geliştiricisiyim. C#, python ve web bilgim var.",
                            IsActive = true,
                            IsDeleted = false,
                            Keywords = "Hasan Erdal, Hasan, Erdal, Software, Developer, Engineer",
                            LogoFA = "<i class=\"fab fa - hire - a - helper\"></i>",
                            LogoText = "HASAN ERDAL",
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 954, DateTimeKind.Local).AddTicks(7569),
                            Note = "InitialCreate",
                            Title = "Hasan Erdal"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PercentageValue")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8848),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8855),
                            Note = "InitialCreate",
                            PercentageValue = 70,
                            Title = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8863),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8864),
                            Note = "InitialCreate",
                            PercentageValue = 60,
                            Title = "ASP.NET MVC"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8868),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8869),
                            Note = "InitialCreate",
                            PercentageValue = 60,
                            Title = "ENTITY FRAMEWORK & LINQ"
                        },
                        new
                        {
                            Id = 4,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8872),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8873),
                            Note = "InitialCreate",
                            PercentageValue = 65,
                            Title = "HTML & CSS"
                        },
                        new
                        {
                            Id = 5,
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8877),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 955, DateTimeKind.Local).AddTicks(8878),
                            Note = "InitialCreate",
                            PercentageValue = 50,
                            Title = "DEVEXPRESS FRAMEWORK"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.SocialMediaAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AccountFA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AccountUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SocialMediaAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountFA = "<i class=\"fab fa - facebook - square\"></i>",
                            AccountUrl = "https://www.facebook.com/xxfiliphasanxx",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1653),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1660),
                            Note = "InitialCreate"
                        },
                        new
                        {
                            Id = 2,
                            AccountFA = "<i class=\"fab fa - twitter - square\"></i>",
                            AccountUrl = "https://twitter.com/hasaerda",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1669),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1671),
                            Note = "InitialCreate"
                        },
                        new
                        {
                            Id = 3,
                            AccountFA = "<i class=\"fab fa - linkedin\"></i>",
                            AccountUrl = "https://www.linkedin.com/in/hasan-erdal-2b57a3136/",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1674),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1675),
                            Note = "InitialCreate"
                        },
                        new
                        {
                            Id = 4,
                            AccountFA = "<i class=\"fab fa - github - square\"></i>",
                            AccountUrl = "https://github.com/Filiphasan",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1679),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1680),
                            Note = "InitialCreate"
                        },
                        new
                        {
                            Id = 5,
                            AccountFA = "<i class=\"fab fa - youtube\"></i>",
                            AccountUrl = "https://www.youtube.com/channel/UCKgQs4J8PEFS97iOGop_X4w",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1683),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 957, DateTimeKind.Local).AddTicks(1684),
                            Note = "InitialCreate"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedByName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Summary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Merhaba siteme hoşgeldiniz. Ben Elektrik Elektronik Mühendisliği okuyan aynı zamanda yazılıma gönül vermiş birisiyim. C# ve .NET alanlarında yoğun bir şekilde kendimi geliştiriyorum. Python ve JavaScript dillerinde ise yavaş ve planlı şekilde gelişimime devam ediyorum. Gelişime açık ve hızlı öğrenen birisi olduğumu düşünüyorum. Geleceğimi yazılım üzerine şekillendireceğime eminim. Bu yolda elimden gelenin en iyisini değil, her şeyi yapacağım. Yazılım üzerine birçok hayalim, uzun ve kısa vadeli planlarım var. Açıkçası yazılımın hayatımın her alanına yeterli ölçüde etki etmesini istiyorum. Bilgisayar eskiden beridir tutkum olan bir alan. Bilgisayardan bir şeyler yazarak bunun somut sonuçlarını görmek beni mutlu ediyor.",
                            CreatedByName = "InitialCreate",
                            CreatedTime = new DateTime(2022, 3, 20, 1, 27, 20, 958, DateTimeKind.Local).AddTicks(544),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedByName = "InitialCreate",
                            ModifiedTime = new DateTime(2022, 3, 20, 1, 27, 20, 958, DateTimeKind.Local).AddTicks(549),
                            Note = "InitialCreate"
                        });
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Article", b =>
                {
                    b.HasOne("MyWebApp.Entities.Concrete.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Comment", b =>
                {
                    b.HasOne("MyWebApp.Entities.Concrete.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Article", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MyWebApp.Entities.Concrete.Category", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
